name: Deploy pages on merge

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - fix/gh-pages-deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages