name: Deploy pages on merge

on:
  pull_request:
    branches:
      - main
  push:
  # JUST FOR TESTING PURPOSES
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install  dependencies
        run: |
          npm install
          npm --prefix ./website install

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH-PAGES-DEPLOY-KEY }}
          publish_dir: ./website