name: Deploy pages on merge

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm --prefix ./website install

    - name: Deploy
      run: |
        git config --global user.name 'BenjaminWills'
        git config --global user.email 'benjaminwills047@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm --prefix ./website run deploy