name: Deploy pages on merge

on:
  pull_request:
    branches:
      - main
  push:
  # JUST FOR TESTING PURPOSES
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install base dependencies
        run: npm install

      - name: Install website dependencies
        run: npm --prefix ./website install

      - name: Authenticate VM
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.MY_GITHUB_TOKEN }}'
          
      - name: Deploy code to pages
        run: |
          make deploy_github_pages