name: Deploy pages on merge

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy code to pages
        run: |
          make deploy_github_pages